#!/bin/bash
sudo apt update
sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils -y

sudo adduser $USER libvirt
sudo adduser $USER kvm

systemctl start libvirtd
systemctl enable libvirtd